//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace interfazGrafica.API_Crud {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="APIGestionCRUDSoap", Namespace="http://tempuri.org/")]
    public partial class APIGestionCRUD : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback InsertarClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerClientePorIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActualizarClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertarPagoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerPagoPorIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActualizarPagoOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarPagoOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertarSedeOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerSedePorIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActualizarSedeOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarSedeOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertarSuscripcionOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerSuscripcionPorIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActualizarSuscripcionOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarSuscripcionOperationCompleted;
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public APIGestionCRUD() {
            this.Url = global::interfazGrafica.Properties.Settings.Default.interfazGrafica_API_Crud_APIGestionCRUD;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event InsertarClienteCompletedEventHandler InsertarClienteCompleted;
        
        /// <remarks/>
        public event ObtenerClientePorIdCompletedEventHandler ObtenerClientePorIdCompleted;
        
        /// <remarks/>
        public event ActualizarClienteCompletedEventHandler ActualizarClienteCompleted;
        
        /// <remarks/>
        public event EliminarClienteCompletedEventHandler EliminarClienteCompleted;
        
        /// <remarks/>
        public event InsertarPagoCompletedEventHandler InsertarPagoCompleted;
        
        /// <remarks/>
        public event ObtenerPagoPorIdCompletedEventHandler ObtenerPagoPorIdCompleted;
        
        /// <remarks/>
        public event ActualizarPagoCompletedEventHandler ActualizarPagoCompleted;
        
        /// <remarks/>
        public event EliminarPagoCompletedEventHandler EliminarPagoCompleted;
        
        /// <remarks/>
        public event InsertarSedeCompletedEventHandler InsertarSedeCompleted;
        
        /// <remarks/>
        public event ObtenerSedePorIdCompletedEventHandler ObtenerSedePorIdCompleted;
        
        /// <remarks/>
        public event ActualizarSedeCompletedEventHandler ActualizarSedeCompleted;
        
        /// <remarks/>
        public event EliminarSedeCompletedEventHandler EliminarSedeCompleted;
        
        /// <remarks/>
        public event InsertarSuscripcionCompletedEventHandler InsertarSuscripcionCompleted;
        
        /// <remarks/>
        public event ObtenerSuscripcionPorIdCompletedEventHandler ObtenerSuscripcionPorIdCompleted;
        
        /// <remarks/>
        public event ActualizarSuscripcionCompletedEventHandler ActualizarSuscripcionCompleted;
        
        /// <remarks/>
        public event EliminarSuscripcionCompletedEventHandler EliminarSuscripcionCompleted;
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertarCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void InsertarCliente(Cliente cliente) {
            this.Invoke("InsertarCliente", new object[] {
                        cliente});
        }
        
        /// <remarks/>
        public void InsertarClienteAsync(Cliente cliente) {
            this.InsertarClienteAsync(cliente, null);
        }
        
        /// <remarks/>
        public void InsertarClienteAsync(Cliente cliente, object userState) {
            if ((this.InsertarClienteOperationCompleted == null)) {
                this.InsertarClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertarClienteOperationCompleted);
            }
            this.InvokeAsync("InsertarCliente", new object[] {
                        cliente}, this.InsertarClienteOperationCompleted, userState);
        }
        
        private void OnInsertarClienteOperationCompleted(object arg) {
            if ((this.InsertarClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertarClienteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerClientePorId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Cliente ObtenerClientePorId(int clienteId) {
            object[] results = this.Invoke("ObtenerClientePorId", new object[] {
                        clienteId});
            return ((Cliente)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerClientePorIdAsync(int clienteId) {
            this.ObtenerClientePorIdAsync(clienteId, null);
        }
        
        /// <remarks/>
        public void ObtenerClientePorIdAsync(int clienteId, object userState) {
            if ((this.ObtenerClientePorIdOperationCompleted == null)) {
                this.ObtenerClientePorIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerClientePorIdOperationCompleted);
            }
            this.InvokeAsync("ObtenerClientePorId", new object[] {
                        clienteId}, this.ObtenerClientePorIdOperationCompleted, userState);
        }
        
        private void OnObtenerClientePorIdOperationCompleted(object arg) {
            if ((this.ObtenerClientePorIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerClientePorIdCompleted(this, new ObtenerClientePorIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ActualizarCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ActualizarCliente(Cliente cliente) {
            this.Invoke("ActualizarCliente", new object[] {
                        cliente});
        }
        
        /// <remarks/>
        public void ActualizarClienteAsync(Cliente cliente) {
            this.ActualizarClienteAsync(cliente, null);
        }
        
        /// <remarks/>
        public void ActualizarClienteAsync(Cliente cliente, object userState) {
            if ((this.ActualizarClienteOperationCompleted == null)) {
                this.ActualizarClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActualizarClienteOperationCompleted);
            }
            this.InvokeAsync("ActualizarCliente", new object[] {
                        cliente}, this.ActualizarClienteOperationCompleted, userState);
        }
        
        private void OnActualizarClienteOperationCompleted(object arg) {
            if ((this.ActualizarClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActualizarClienteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EliminarCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EliminarCliente(int clienteId) {
            this.Invoke("EliminarCliente", new object[] {
                        clienteId});
        }
        
        /// <remarks/>
        public void EliminarClienteAsync(int clienteId) {
            this.EliminarClienteAsync(clienteId, null);
        }
        
        /// <remarks/>
        public void EliminarClienteAsync(int clienteId, object userState) {
            if ((this.EliminarClienteOperationCompleted == null)) {
                this.EliminarClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarClienteOperationCompleted);
            }
            this.InvokeAsync("EliminarCliente", new object[] {
                        clienteId}, this.EliminarClienteOperationCompleted, userState);
        }
        
        private void OnEliminarClienteOperationCompleted(object arg) {
            if ((this.EliminarClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarClienteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertarPago", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void InsertarPago(Pago pago) {
            this.Invoke("InsertarPago", new object[] {
                        pago});
        }
        
        /// <remarks/>
        public void InsertarPagoAsync(Pago pago) {
            this.InsertarPagoAsync(pago, null);
        }
        
        /// <remarks/>
        public void InsertarPagoAsync(Pago pago, object userState) {
            if ((this.InsertarPagoOperationCompleted == null)) {
                this.InsertarPagoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertarPagoOperationCompleted);
            }
            this.InvokeAsync("InsertarPago", new object[] {
                        pago}, this.InsertarPagoOperationCompleted, userState);
        }
        
        private void OnInsertarPagoOperationCompleted(object arg) {
            if ((this.InsertarPagoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertarPagoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerPagoPorId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Pago ObtenerPagoPorId(int pagoId) {
            object[] results = this.Invoke("ObtenerPagoPorId", new object[] {
                        pagoId});
            return ((Pago)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerPagoPorIdAsync(int pagoId) {
            this.ObtenerPagoPorIdAsync(pagoId, null);
        }
        
        /// <remarks/>
        public void ObtenerPagoPorIdAsync(int pagoId, object userState) {
            if ((this.ObtenerPagoPorIdOperationCompleted == null)) {
                this.ObtenerPagoPorIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerPagoPorIdOperationCompleted);
            }
            this.InvokeAsync("ObtenerPagoPorId", new object[] {
                        pagoId}, this.ObtenerPagoPorIdOperationCompleted, userState);
        }
        
        private void OnObtenerPagoPorIdOperationCompleted(object arg) {
            if ((this.ObtenerPagoPorIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerPagoPorIdCompleted(this, new ObtenerPagoPorIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ActualizarPago", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ActualizarPago(Pago pago) {
            this.Invoke("ActualizarPago", new object[] {
                        pago});
        }
        
        /// <remarks/>
        public void ActualizarPagoAsync(Pago pago) {
            this.ActualizarPagoAsync(pago, null);
        }
        
        /// <remarks/>
        public void ActualizarPagoAsync(Pago pago, object userState) {
            if ((this.ActualizarPagoOperationCompleted == null)) {
                this.ActualizarPagoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActualizarPagoOperationCompleted);
            }
            this.InvokeAsync("ActualizarPago", new object[] {
                        pago}, this.ActualizarPagoOperationCompleted, userState);
        }
        
        private void OnActualizarPagoOperationCompleted(object arg) {
            if ((this.ActualizarPagoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActualizarPagoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EliminarPago", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EliminarPago(int pagoId) {
            this.Invoke("EliminarPago", new object[] {
                        pagoId});
        }
        
        /// <remarks/>
        public void EliminarPagoAsync(int pagoId) {
            this.EliminarPagoAsync(pagoId, null);
        }
        
        /// <remarks/>
        public void EliminarPagoAsync(int pagoId, object userState) {
            if ((this.EliminarPagoOperationCompleted == null)) {
                this.EliminarPagoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarPagoOperationCompleted);
            }
            this.InvokeAsync("EliminarPago", new object[] {
                        pagoId}, this.EliminarPagoOperationCompleted, userState);
        }
        
        private void OnEliminarPagoOperationCompleted(object arg) {
            if ((this.EliminarPagoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarPagoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertarSede", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void InsertarSede(Sede sede) {
            this.Invoke("InsertarSede", new object[] {
                        sede});
        }
        
        /// <remarks/>
        public void InsertarSedeAsync(Sede sede) {
            this.InsertarSedeAsync(sede, null);
        }
        
        /// <remarks/>
        public void InsertarSedeAsync(Sede sede, object userState) {
            if ((this.InsertarSedeOperationCompleted == null)) {
                this.InsertarSedeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertarSedeOperationCompleted);
            }
            this.InvokeAsync("InsertarSede", new object[] {
                        sede}, this.InsertarSedeOperationCompleted, userState);
        }
        
        private void OnInsertarSedeOperationCompleted(object arg) {
            if ((this.InsertarSedeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertarSedeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerSedePorId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Sede ObtenerSedePorId(int sedeId) {
            object[] results = this.Invoke("ObtenerSedePorId", new object[] {
                        sedeId});
            return ((Sede)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerSedePorIdAsync(int sedeId) {
            this.ObtenerSedePorIdAsync(sedeId, null);
        }
        
        /// <remarks/>
        public void ObtenerSedePorIdAsync(int sedeId, object userState) {
            if ((this.ObtenerSedePorIdOperationCompleted == null)) {
                this.ObtenerSedePorIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerSedePorIdOperationCompleted);
            }
            this.InvokeAsync("ObtenerSedePorId", new object[] {
                        sedeId}, this.ObtenerSedePorIdOperationCompleted, userState);
        }
        
        private void OnObtenerSedePorIdOperationCompleted(object arg) {
            if ((this.ObtenerSedePorIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerSedePorIdCompleted(this, new ObtenerSedePorIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ActualizarSede", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ActualizarSede(Sede sede) {
            this.Invoke("ActualizarSede", new object[] {
                        sede});
        }
        
        /// <remarks/>
        public void ActualizarSedeAsync(Sede sede) {
            this.ActualizarSedeAsync(sede, null);
        }
        
        /// <remarks/>
        public void ActualizarSedeAsync(Sede sede, object userState) {
            if ((this.ActualizarSedeOperationCompleted == null)) {
                this.ActualizarSedeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActualizarSedeOperationCompleted);
            }
            this.InvokeAsync("ActualizarSede", new object[] {
                        sede}, this.ActualizarSedeOperationCompleted, userState);
        }
        
        private void OnActualizarSedeOperationCompleted(object arg) {
            if ((this.ActualizarSedeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActualizarSedeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EliminarSede", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EliminarSede(int sedeId) {
            this.Invoke("EliminarSede", new object[] {
                        sedeId});
        }
        
        /// <remarks/>
        public void EliminarSedeAsync(int sedeId) {
            this.EliminarSedeAsync(sedeId, null);
        }
        
        /// <remarks/>
        public void EliminarSedeAsync(int sedeId, object userState) {
            if ((this.EliminarSedeOperationCompleted == null)) {
                this.EliminarSedeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarSedeOperationCompleted);
            }
            this.InvokeAsync("EliminarSede", new object[] {
                        sedeId}, this.EliminarSedeOperationCompleted, userState);
        }
        
        private void OnEliminarSedeOperationCompleted(object arg) {
            if ((this.EliminarSedeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarSedeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertarSuscripcion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void InsertarSuscripcion(Suscripcione suscripcion) {
            this.Invoke("InsertarSuscripcion", new object[] {
                        suscripcion});
        }
        
        /// <remarks/>
        public void InsertarSuscripcionAsync(Suscripcione suscripcion) {
            this.InsertarSuscripcionAsync(suscripcion, null);
        }
        
        /// <remarks/>
        public void InsertarSuscripcionAsync(Suscripcione suscripcion, object userState) {
            if ((this.InsertarSuscripcionOperationCompleted == null)) {
                this.InsertarSuscripcionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertarSuscripcionOperationCompleted);
            }
            this.InvokeAsync("InsertarSuscripcion", new object[] {
                        suscripcion}, this.InsertarSuscripcionOperationCompleted, userState);
        }
        
        private void OnInsertarSuscripcionOperationCompleted(object arg) {
            if ((this.InsertarSuscripcionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertarSuscripcionCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerSuscripcionPorId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Suscripcione ObtenerSuscripcionPorId(int suscripcionId) {
            object[] results = this.Invoke("ObtenerSuscripcionPorId", new object[] {
                        suscripcionId});
            return ((Suscripcione)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerSuscripcionPorIdAsync(int suscripcionId) {
            this.ObtenerSuscripcionPorIdAsync(suscripcionId, null);
        }
        
        /// <remarks/>
        public void ObtenerSuscripcionPorIdAsync(int suscripcionId, object userState) {
            if ((this.ObtenerSuscripcionPorIdOperationCompleted == null)) {
                this.ObtenerSuscripcionPorIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerSuscripcionPorIdOperationCompleted);
            }
            this.InvokeAsync("ObtenerSuscripcionPorId", new object[] {
                        suscripcionId}, this.ObtenerSuscripcionPorIdOperationCompleted, userState);
        }
        
        private void OnObtenerSuscripcionPorIdOperationCompleted(object arg) {
            if ((this.ObtenerSuscripcionPorIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerSuscripcionPorIdCompleted(this, new ObtenerSuscripcionPorIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ActualizarSuscripcion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ActualizarSuscripcion(Suscripcione suscripcion) {
            this.Invoke("ActualizarSuscripcion", new object[] {
                        suscripcion});
        }
        
        /// <remarks/>
        public void ActualizarSuscripcionAsync(Suscripcione suscripcion) {
            this.ActualizarSuscripcionAsync(suscripcion, null);
        }
        
        /// <remarks/>
        public void ActualizarSuscripcionAsync(Suscripcione suscripcion, object userState) {
            if ((this.ActualizarSuscripcionOperationCompleted == null)) {
                this.ActualizarSuscripcionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActualizarSuscripcionOperationCompleted);
            }
            this.InvokeAsync("ActualizarSuscripcion", new object[] {
                        suscripcion}, this.ActualizarSuscripcionOperationCompleted, userState);
        }
        
        private void OnActualizarSuscripcionOperationCompleted(object arg) {
            if ((this.ActualizarSuscripcionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActualizarSuscripcionCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EliminarSuscripcion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EliminarSuscripcion(int suscripcionId) {
            this.Invoke("EliminarSuscripcion", new object[] {
                        suscripcionId});
        }
        
        /// <remarks/>
        public void EliminarSuscripcionAsync(int suscripcionId) {
            this.EliminarSuscripcionAsync(suscripcionId, null);
        }
        
        /// <remarks/>
        public void EliminarSuscripcionAsync(int suscripcionId, object userState) {
            if ((this.EliminarSuscripcionOperationCompleted == null)) {
                this.EliminarSuscripcionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarSuscripcionOperationCompleted);
            }
            this.InvokeAsync("EliminarSuscripcion", new object[] {
                        suscripcionId}, this.EliminarSuscripcionOperationCompleted, userState);
        }
        
        private void OnEliminarSuscripcionOperationCompleted(object arg) {
            if ((this.EliminarSuscripcionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarSuscripcionCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Cliente {
        
        private int clienteIDField;
        
        private string nombreField;
        
        private string apellidoField;
        
        private string emailField;
        
        private string telefonoField;
        
        private System.Nullable<System.DateTime> fechaRegistroField;
        
        private string cedulaField;
        
        private System.Nullable<bool> activoField;
        
        private Suscripcione[] suscripcionesField;
        
        /// <remarks/>
        public int ClienteID {
            get {
                return this.clienteIDField;
            }
            set {
                this.clienteIDField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string Apellido {
            get {
                return this.apellidoField;
            }
            set {
                this.apellidoField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> FechaRegistro {
            get {
                return this.fechaRegistroField;
            }
            set {
                this.fechaRegistroField = value;
            }
        }
        
        /// <remarks/>
        public string Cedula {
            get {
                return this.cedulaField;
            }
            set {
                this.cedulaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> Activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
            }
        }
        
        /// <remarks/>
        public Suscripcione[] Suscripciones {
            get {
                return this.suscripcionesField;
            }
            set {
                this.suscripcionesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Suscripcione {
        
        private int suscripcionIDField;
        
        private System.Nullable<int> clienteIDField;
        
        private System.Nullable<int> sedeIDField;
        
        private System.Nullable<System.DateTime> fechaInicioField;
        
        private string tipoSuscripcionField;
        
        private string estadoField;
        
        private System.Nullable<bool> activoField;
        
        private Cliente clienteField;
        
        private Pago[] pagosField;
        
        private Sede sedeField;
        
        /// <remarks/>
        public int SuscripcionID {
            get {
                return this.suscripcionIDField;
            }
            set {
                this.suscripcionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ClienteID {
            get {
                return this.clienteIDField;
            }
            set {
                this.clienteIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> SedeID {
            get {
                return this.sedeIDField;
            }
            set {
                this.sedeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> FechaInicio {
            get {
                return this.fechaInicioField;
            }
            set {
                this.fechaInicioField = value;
            }
        }
        
        /// <remarks/>
        public string TipoSuscripcion {
            get {
                return this.tipoSuscripcionField;
            }
            set {
                this.tipoSuscripcionField = value;
            }
        }
        
        /// <remarks/>
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> Activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
            }
        }
        
        /// <remarks/>
        public Cliente Cliente {
            get {
                return this.clienteField;
            }
            set {
                this.clienteField = value;
            }
        }
        
        /// <remarks/>
        public Pago[] Pagos {
            get {
                return this.pagosField;
            }
            set {
                this.pagosField = value;
            }
        }
        
        /// <remarks/>
        public Sede Sede {
            get {
                return this.sedeField;
            }
            set {
                this.sedeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Pago {
        
        private int pagoIDField;
        
        private System.Nullable<int> suscripcionIDField;
        
        private System.Nullable<System.DateTime> fechaPagoField;
        
        private System.Nullable<decimal> montoField;
        
        private string metodoPagoField;
        
        private System.Nullable<bool> activoField;
        
        private Suscripcione suscripcioneField;
        
        /// <remarks/>
        public int PagoID {
            get {
                return this.pagoIDField;
            }
            set {
                this.pagoIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> SuscripcionID {
            get {
                return this.suscripcionIDField;
            }
            set {
                this.suscripcionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> FechaPago {
            get {
                return this.fechaPagoField;
            }
            set {
                this.fechaPagoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> Monto {
            get {
                return this.montoField;
            }
            set {
                this.montoField = value;
            }
        }
        
        /// <remarks/>
        public string MetodoPago {
            get {
                return this.metodoPagoField;
            }
            set {
                this.metodoPagoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> Activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
            }
        }
        
        /// <remarks/>
        public Suscripcione Suscripcione {
            get {
                return this.suscripcioneField;
            }
            set {
                this.suscripcioneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Sede {
        
        private int sedeIDField;
        
        private string nombreSedeField;
        
        private string direccionField;
        
        private string telefonoField;
        
        private System.Nullable<bool> activoField;
        
        private Suscripcione[] suscripcionesField;
        
        /// <remarks/>
        public int SedeID {
            get {
                return this.sedeIDField;
            }
            set {
                this.sedeIDField = value;
            }
        }
        
        /// <remarks/>
        public string NombreSede {
            get {
                return this.nombreSedeField;
            }
            set {
                this.nombreSedeField = value;
            }
        }
        
        /// <remarks/>
        public string Direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
            }
        }
        
        /// <remarks/>
        public string Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> Activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
            }
        }
        
        /// <remarks/>
        public Suscripcione[] Suscripciones {
            get {
                return this.suscripcionesField;
            }
            set {
                this.suscripcionesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void InsertarClienteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ObtenerClientePorIdCompletedEventHandler(object sender, ObtenerClientePorIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerClientePorIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerClientePorIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Cliente Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cliente)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ActualizarClienteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void EliminarClienteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void InsertarPagoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ObtenerPagoPorIdCompletedEventHandler(object sender, ObtenerPagoPorIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerPagoPorIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerPagoPorIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Pago Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Pago)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ActualizarPagoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void EliminarPagoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void InsertarSedeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ObtenerSedePorIdCompletedEventHandler(object sender, ObtenerSedePorIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerSedePorIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerSedePorIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Sede Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Sede)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ActualizarSedeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void EliminarSedeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void InsertarSuscripcionCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ObtenerSuscripcionPorIdCompletedEventHandler(object sender, ObtenerSuscripcionPorIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerSuscripcionPorIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerSuscripcionPorIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Suscripcione Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Suscripcione)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ActualizarSuscripcionCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void EliminarSuscripcionCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591