//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace interfazGrafica.Api_Consultas {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="API_GestionConsultasSoap", Namespace="http://tempuri.org/")]
    public partial class API_GestionConsultas : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ListarClientesOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarPagosOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarSedesOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarSuscripcionesOperationCompleted;
        
        private System.Threading.SendOrPostCallback clientesConDeudasOperationCompleted;
        
        private System.Threading.SendOrPostCallback sedesConMasSuscripcionesOperationCompleted;
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public API_GestionConsultas() {
            this.Url = global::interfazGrafica.Properties.Settings.Default.interfazGrafica_Api_Consultas_API_GestionConsultas;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ListarClientesCompletedEventHandler ListarClientesCompleted;
        
        /// <remarks/>
        public event ListarPagosCompletedEventHandler ListarPagosCompleted;
        
        /// <remarks/>
        public event ListarSedesCompletedEventHandler ListarSedesCompleted;
        
        /// <remarks/>
        public event ListarSuscripcionesCompletedEventHandler ListarSuscripcionesCompleted;
        
        /// <remarks/>
        public event clientesConDeudasCompletedEventHandler clientesConDeudasCompleted;
        
        /// <remarks/>
        public event sedesConMasSuscripcionesCompletedEventHandler sedesConMasSuscripcionesCompleted;
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarClientes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SP_ListClientes_Result[] ListarClientes() {
            object[] results = this.Invoke("ListarClientes", new object[0]);
            return ((SP_ListClientes_Result[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarClientesAsync() {
            this.ListarClientesAsync(null);
        }
        
        /// <remarks/>
        public void ListarClientesAsync(object userState) {
            if ((this.ListarClientesOperationCompleted == null)) {
                this.ListarClientesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarClientesOperationCompleted);
            }
            this.InvokeAsync("ListarClientes", new object[0], this.ListarClientesOperationCompleted, userState);
        }
        
        private void OnListarClientesOperationCompleted(object arg) {
            if ((this.ListarClientesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarClientesCompleted(this, new ListarClientesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarPagos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SP_ListPagos_Result[] ListarPagos() {
            object[] results = this.Invoke("ListarPagos", new object[0]);
            return ((SP_ListPagos_Result[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarPagosAsync() {
            this.ListarPagosAsync(null);
        }
        
        /// <remarks/>
        public void ListarPagosAsync(object userState) {
            if ((this.ListarPagosOperationCompleted == null)) {
                this.ListarPagosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarPagosOperationCompleted);
            }
            this.InvokeAsync("ListarPagos", new object[0], this.ListarPagosOperationCompleted, userState);
        }
        
        private void OnListarPagosOperationCompleted(object arg) {
            if ((this.ListarPagosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarPagosCompleted(this, new ListarPagosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarSedes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SP_ListSedes_Result[] ListarSedes() {
            object[] results = this.Invoke("ListarSedes", new object[0]);
            return ((SP_ListSedes_Result[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarSedesAsync() {
            this.ListarSedesAsync(null);
        }
        
        /// <remarks/>
        public void ListarSedesAsync(object userState) {
            if ((this.ListarSedesOperationCompleted == null)) {
                this.ListarSedesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarSedesOperationCompleted);
            }
            this.InvokeAsync("ListarSedes", new object[0], this.ListarSedesOperationCompleted, userState);
        }
        
        private void OnListarSedesOperationCompleted(object arg) {
            if ((this.ListarSedesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarSedesCompleted(this, new ListarSedesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarSuscripciones", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SP_ListSuscripciones_Result[] ListarSuscripciones() {
            object[] results = this.Invoke("ListarSuscripciones", new object[0]);
            return ((SP_ListSuscripciones_Result[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarSuscripcionesAsync() {
            this.ListarSuscripcionesAsync(null);
        }
        
        /// <remarks/>
        public void ListarSuscripcionesAsync(object userState) {
            if ((this.ListarSuscripcionesOperationCompleted == null)) {
                this.ListarSuscripcionesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarSuscripcionesOperationCompleted);
            }
            this.InvokeAsync("ListarSuscripciones", new object[0], this.ListarSuscripcionesOperationCompleted, userState);
        }
        
        private void OnListarSuscripcionesOperationCompleted(object arg) {
            if ((this.ListarSuscripcionesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarSuscripcionesCompleted(this, new ListarSuscripcionesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/clientesConDeudas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SP_ClientesConDeuda_Result[] clientesConDeudas() {
            object[] results = this.Invoke("clientesConDeudas", new object[0]);
            return ((SP_ClientesConDeuda_Result[])(results[0]));
        }
        
        /// <remarks/>
        public void clientesConDeudasAsync() {
            this.clientesConDeudasAsync(null);
        }
        
        /// <remarks/>
        public void clientesConDeudasAsync(object userState) {
            if ((this.clientesConDeudasOperationCompleted == null)) {
                this.clientesConDeudasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnclientesConDeudasOperationCompleted);
            }
            this.InvokeAsync("clientesConDeudas", new object[0], this.clientesConDeudasOperationCompleted, userState);
        }
        
        private void OnclientesConDeudasOperationCompleted(object arg) {
            if ((this.clientesConDeudasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.clientesConDeudasCompleted(this, new clientesConDeudasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/sedesConMasSuscripciones", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SP_SedeConMasSuscripcionesActivas_Result[] sedesConMasSuscripciones() {
            object[] results = this.Invoke("sedesConMasSuscripciones", new object[0]);
            return ((SP_SedeConMasSuscripcionesActivas_Result[])(results[0]));
        }
        
        /// <remarks/>
        public void sedesConMasSuscripcionesAsync() {
            this.sedesConMasSuscripcionesAsync(null);
        }
        
        /// <remarks/>
        public void sedesConMasSuscripcionesAsync(object userState) {
            if ((this.sedesConMasSuscripcionesOperationCompleted == null)) {
                this.sedesConMasSuscripcionesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsedesConMasSuscripcionesOperationCompleted);
            }
            this.InvokeAsync("sedesConMasSuscripciones", new object[0], this.sedesConMasSuscripcionesOperationCompleted, userState);
        }
        
        private void OnsedesConMasSuscripcionesOperationCompleted(object arg) {
            if ((this.sedesConMasSuscripcionesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sedesConMasSuscripcionesCompleted(this, new sedesConMasSuscripcionesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SP_ListClientes_Result {
        
        private int clienteIDField;
        
        private string nombreField;
        
        private string apellidoField;
        
        private string emailField;
        
        private string telefonoField;
        
        private System.Nullable<System.DateTime> fechaRegistroField;
        
        private string cedulaField;
        
        private System.Nullable<bool> activoField;
        
        /// <remarks/>
        public int ClienteID {
            get {
                return this.clienteIDField;
            }
            set {
                this.clienteIDField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string Apellido {
            get {
                return this.apellidoField;
            }
            set {
                this.apellidoField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> FechaRegistro {
            get {
                return this.fechaRegistroField;
            }
            set {
                this.fechaRegistroField = value;
            }
        }
        
        /// <remarks/>
        public string Cedula {
            get {
                return this.cedulaField;
            }
            set {
                this.cedulaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> Activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SP_SedeConMasSuscripcionesActivas_Result {
        
        private string nombreSedeField;
        
        private System.Nullable<int> totalSuscripcionesField;
        
        /// <remarks/>
        public string NombreSede {
            get {
                return this.nombreSedeField;
            }
            set {
                this.nombreSedeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> TotalSuscripciones {
            get {
                return this.totalSuscripcionesField;
            }
            set {
                this.totalSuscripcionesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SP_ClientesConDeuda_Result {
        
        private int clienteIDField;
        
        private string nombreField;
        
        private string apellidoField;
        
        private System.Nullable<decimal> deudaTotalField;
        
        /// <remarks/>
        public int ClienteID {
            get {
                return this.clienteIDField;
            }
            set {
                this.clienteIDField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string Apellido {
            get {
                return this.apellidoField;
            }
            set {
                this.apellidoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> DeudaTotal {
            get {
                return this.deudaTotalField;
            }
            set {
                this.deudaTotalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SP_ListSuscripciones_Result {
        
        private int suscripcionIDField;
        
        private System.Nullable<int> clienteIDField;
        
        private System.Nullable<int> sedeIDField;
        
        private System.Nullable<System.DateTime> fechaInicioField;
        
        private string tipoSuscripcionField;
        
        private string estadoField;
        
        private System.Nullable<bool> activoField;
        
        /// <remarks/>
        public int SuscripcionID {
            get {
                return this.suscripcionIDField;
            }
            set {
                this.suscripcionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ClienteID {
            get {
                return this.clienteIDField;
            }
            set {
                this.clienteIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> SedeID {
            get {
                return this.sedeIDField;
            }
            set {
                this.sedeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> FechaInicio {
            get {
                return this.fechaInicioField;
            }
            set {
                this.fechaInicioField = value;
            }
        }
        
        /// <remarks/>
        public string TipoSuscripcion {
            get {
                return this.tipoSuscripcionField;
            }
            set {
                this.tipoSuscripcionField = value;
            }
        }
        
        /// <remarks/>
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> Activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SP_ListSedes_Result {
        
        private int sedeIDField;
        
        private string nombreSedeField;
        
        private string direccionField;
        
        private string telefonoField;
        
        private System.Nullable<bool> activoField;
        
        /// <remarks/>
        public int SedeID {
            get {
                return this.sedeIDField;
            }
            set {
                this.sedeIDField = value;
            }
        }
        
        /// <remarks/>
        public string NombreSede {
            get {
                return this.nombreSedeField;
            }
            set {
                this.nombreSedeField = value;
            }
        }
        
        /// <remarks/>
        public string Direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
            }
        }
        
        /// <remarks/>
        public string Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> Activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SP_ListPagos_Result {
        
        private int pagoIDField;
        
        private System.Nullable<int> suscripcionIDField;
        
        private System.Nullable<System.DateTime> fechaPagoField;
        
        private System.Nullable<decimal> montoField;
        
        private string metodoPagoField;
        
        private System.Nullable<bool> activoField;
        
        /// <remarks/>
        public int PagoID {
            get {
                return this.pagoIDField;
            }
            set {
                this.pagoIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> SuscripcionID {
            get {
                return this.suscripcionIDField;
            }
            set {
                this.suscripcionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> FechaPago {
            get {
                return this.fechaPagoField;
            }
            set {
                this.fechaPagoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> Monto {
            get {
                return this.montoField;
            }
            set {
                this.montoField = value;
            }
        }
        
        /// <remarks/>
        public string MetodoPago {
            get {
                return this.metodoPagoField;
            }
            set {
                this.metodoPagoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> Activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ListarClientesCompletedEventHandler(object sender, ListarClientesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarClientesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarClientesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SP_ListClientes_Result[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SP_ListClientes_Result[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ListarPagosCompletedEventHandler(object sender, ListarPagosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarPagosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarPagosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SP_ListPagos_Result[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SP_ListPagos_Result[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ListarSedesCompletedEventHandler(object sender, ListarSedesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarSedesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarSedesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SP_ListSedes_Result[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SP_ListSedes_Result[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ListarSuscripcionesCompletedEventHandler(object sender, ListarSuscripcionesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarSuscripcionesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarSuscripcionesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SP_ListSuscripciones_Result[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SP_ListSuscripciones_Result[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void clientesConDeudasCompletedEventHandler(object sender, clientesConDeudasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class clientesConDeudasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal clientesConDeudasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SP_ClientesConDeuda_Result[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SP_ClientesConDeuda_Result[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void sedesConMasSuscripcionesCompletedEventHandler(object sender, sedesConMasSuscripcionesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sedesConMasSuscripcionesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sedesConMasSuscripcionesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SP_SedeConMasSuscripcionesActivas_Result[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SP_SedeConMasSuscripcionesActivas_Result[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591